defaultInterval: &interval
    days: 0
    hours: 0
    minutes: 0
    seconds: 0

ingester:
    FILE_INGEST_REQUEST: AT_FILE_INGEST_REQUEST
    CONSUME_QUEUE: at_publish_to_oods
    PUBLISH_QUEUE: oods_publish_to_at
    forwarderStagingDirectory: /data/staging/auxTel/oods
    baseBrokerAddr: localhost/%2ftest_at
    butlers: 
        - butler:
            class:
                import : lsst.ctrl.oods.gen2ButlerIngester
                name : Gen2ButlerIngester
            stagingDirectory:  /data/lsstdata/NTS/auxTel/oods/butler/staging
            badFileDirectory: /data/lsstdata/NTS/auxTel/oods/butler/badfiles
            repoDirectory : /data/lsstdata/NTS/auxTel/oods/butler/repo
        - butler:
            instrument: lsst.obs.lsst.Latiss
            class:
                import : lsst.ctrl.oods.gen3ButlerIngester
                name : Gen3ButlerIngester
            stagingDirectory : /data/lsstdata/NTS/auxTel/oods/gen3butler/raw
            badFileDirectory: /data/lsstdata/NTS/auxTel/oods/gen3butler/badfiles
            repoDirectory : /repo/LATISS
            collections:
                - LATISS/raw/all
            scanInterval:
                <<: *interval
                minutes: 1
            filesOlderThan:
                <<: *interval
                days: 30
    batchSize: 20
    scanInterval:
        <<: *interval
        seconds: 2

cacheCleaner:
    directories:
        - /data/lsstdata/NTS/auxTel/oods/butler/repo/raw
        - /data/lsstdata/NTS/auxTel/oods/butler/badfiles
        - /data/lsstdata/NTS/auxTel/oods/butler/staging
        - /data/lsstdata/NTS/auxTel/oods/gen3butler/badfiles
        - /data/staging/auxTel/oods
        - /data/staging/auxTel/forwarder
    scanInterval:
        <<: *interval
        seconds: 30
    filesOlderThan:
        <<: *interval
        days: 30 
    directoriesEmptyForMoreThan:
        <<: *interval
        days: 2
