defaultInterval: &interval
    days: 0
    hours: 0
    minutes: 0
    seconds: 0

ingester:
    FILE_INGEST_REQUEST: CC_FILE_INGEST_REQUEST
    CONSUME_QUEUE: cc_publish_to_oods
    PUBLISH_QUEUE: oods_publish_to_cc
    directories:
        - /data/staging/comcam/oods
    baseBrokerAddr: localhost/%2ftest_cc
    badFileDirectory: /data/lsstdata/NTS/comcam/oods/badfiles
    butler:
        class:
            import : lsst.ctrl.oods.gen2ButlerIngester
            name : Gen2ButlerIngester
        repoDirectory : /data/lsstdata/NTS/comcam/oods/butler/repo
    batchSize: 20
    scanInterval:
        <<: *interval
        seconds: 1

cacheCleaner:
    directories:
        - /data/lsstdata/NTS/comcam/oods/butler/repo/raw
        - /data/lsstdata/NTS/comcam/oods/badfiles
        - /data/staging/cc_oods
    scanInterval:
        <<: *interval
        seconds: 30
    filesOlderThan:
        <<: *interval
        days: 30 
    directoriesEmptyForMoreThan:
        <<: *interval
        days: 2
