defaultInterval: &interval
    days: 0
    hours: 0
    minutes: 0
    seconds: 0

ingester:
    imageStagingDirectory: /data/staging/lsstcam/oods
    butlers:
        - butler:
            instrument: lsst.obs.lsst.LsstCam
            class:
                import : lsst.ctrl.oods.gen3ButlerIngester
                name : Gen3ButlerIngester
            stagingDirectory : /data/lsstdata/base/lsstcam/oods/gen3butler/raw
            badFileDirectory: /data/lsstdata/base/lsstcam/oods/gen3butler/badfiles
            repoDirectory : /repo/LSSTCam
            collections:
                - LSSTCam/raw/all
            scanInterval:
                <<: *interval
                hours: 1
            filesOlderThan:
                <<: *interval
                days: 90
    batchSize: 20
    scanInterval:
        <<: *interval
        seconds: 2

cacheCleaner:
    # ONLY clean out empty directories here, never files
    clearEmptyDirectories:
        - /data/lsstdata/base/lsstcam/oods/gen3butler/raw
    # clean out empty directories and old files from these directories
    clearEmptyDirectoriesAndOldFiles:
        - /data/staging/lsstcam/oods
        - /data/lsstdata/base/lsstcam/oods/gen3butler/badfiles
        - /data/staging/lsstcam/forwarder
    scanInterval:
        <<: *interval
        hours: 1
    filesOlderThan:
        <<: *interval
        days: 31
    directoriesEmptyForMoreThan:
        <<: *interval
        days: 2
