# Configuration settings for ATArchiver
ROOT:
  REDIS_HOST: localhost
  ARCHIVER_REDIS_DB: 15
  FORWARDER_PUBLISH_QUEUE: at_foreman_ack_publish
  OODS_PUBLISH_QUEUE: at_publish_to_oods
  OODS_CONSUME_QUEUE: oods_publish_to_at
  ARCHIVE_CTRL_PUBLISH_QUEUE: archive_ctrl_publish # this should probably be at_archive_ctrl_publish
  ARCHIVE_CTRL_CONSUME_QUEUE: archive_ctrl_consume # this should probably be at_archive_ctrl_consume
  TELEMETRY_QUEUE: telemetry_queue # this should probably be at_telemetry_queue
  CAMERA_NAME: LATISS
  ARCHIVER_NAME: ATArchiver
  SHORT_NAME: AT

  ARCHIVE_CONTROLLER_NAME: at_archive_controller
  ASSOCIATION_KEY: atarchiver_association
  # message types
  FWDR_HEALTH_CHECK_ACK: AT_FWDR_HEALTH_CHECK_ACK
  FILE_INGEST_REQUEST: AT_FILE_INGEST_REQUEST
  NEW_ARCHIVE_ITEM: NEW_AT_ARCHIVE_ITEM
  FWDR_XFER_PARAMS: AT_FWDR_XFER_PARAMS
  FWDR_END_READOUT: AT_FWDR_END_READOUT
  FWDR_HEADER_READY: AT_FWDR_HEADER_READY

  ACK_TIMEOUT: 10

  CSC:
    BEACON:
        SECONDS_TO_EXPIRE: 10
        SECONDS_TO_UPDATE: 3

  BASE_BROKER_ADDR: 139.229.170.34:5672/%2ftest_at
  ARCHIVE:
    ARCHIVE_LOGIN: arc
    ARCHIVE_IP: 139.227.170.34
    CHECKSUM_TYPE: MD5   # Current available options: MD5, CRC-32 
    FORWARDER_STAGING: /data/staging/atforwarder
    OODS_STAGING: /data/staging/oods
    DBB_STAGING: /data/staging/dbb
  ATS:
    WFS_RAFT: "00"
    WFS_CCD: [ "00" ]
