# Configuration settings for CCArchiver
ROOT:
  REDIS_HOST: localhost
  ARCHIVER_REDIS_DB: 14
  FORWARDER_PUBLISH_QUEUE: cc_foreman_ack_publish
  OODS_PUBLISH_QUEUE: cc_publish_to_oods
  OODS_CONSUME_QUEUE: oods_publish_to_cc
  ARCHIVE_CTRL_PUBLISH_QUEUE: archive_ctrl_publish
  ARCHIVE_CTRL_CONSUME_QUEUE: archive_ctrl_consume
  TELEMETRY_QUEUE: telemetry_queue
  CAMERA_NAME: COMCAM
  ARCHIVER_NAME: CCArchiver
  SHORT_NAME: CC

  ARCHIVE_CONTROLLER_NAME: cc_archive_controller
  ASSOCIATION_KEY: ccarchiver_association
  # message types
  FWDR_HEALTH_CHECK_ACK: CC_FWDR_HEALTH_CHECK_ACK
  FILE_INGEST_REQUEST: CC_FILE_INGEST_REQUEST
  NEW_ARCHIVE_ITEM: NEW_CC_ARCHIVE_ITEM
  FWDR_XFER_PARAMS: CC_FWDR_XFER_PARAMS
  FWDR_END_READOUT: CC_FWDR_END_READOUT
  FWDR_HEADER_READY: CC_FWDR_HEADER_READY

  ACK_TIMEOUT: 10

  CSC:
    BEACON:
        SECONDS_TO_EXPIRE: 10
        SECONDS_TO_UPDATE: 3

  BASE_BROKER_ADDR: 139.229.170.34:5672/%2ftest_cc
  ARCHIVE:
    ARCHIVE_LOGIN: ARC
    ARCHIVE_IP: 139.229.170.34
    CHECKSUM_TYPE: MD5   # Current available options: MD5, CRC-32 
    FORWARDER_STAGING: /data/staging/ccforwarder
    OODS_STAGING: /data/staging/oods
    DBB_STAGING: /data/staging/dbb
  ATS:
    WFS_RAFT: "00"
    WFS_CCD: [ "00" ]
