# docker-compose version of this compose file
version: "3.7"

services:
  oods:
    image: ts-dockerhub.lsst.org/oods:${OODS_TAG_VERSION}_${CYCLE_TAG}
    build:
      context: ./oods
      args:
        - CYCLE_TAG
        - CTRL_OODS_GIT
        - TS_DDSCONFIG_PACKAGE

  atoods:
    image: ts-dockerhub.lsst.org/atoods:${OODS_TAG_VERSION}_${CYCLE_TAG}
    build:
      context: ./atoods
      args:
        - CYCLE_TAG

  ccoods:
    image: ts-dockerhub.lsst.org/ccoods:${OODS_TAG_VERSION}_${CYCLE_TAG}
    build:
      context: ./ccoods
      args:
        - CYCLE_TAG

  test-oods:
    image: ts-dockerhub.lsst.org/test-oods:${OODS_TAG_VERSION}_${CYCLE_TAG}
    build:
      context: ./test_oods
      args:
        - CYCLE_TAG
        - TS_DDSCONFIG_PACKAGE
    environment:
        - OODS_CONFIG_FILE=/home/saluser/config/cc_oods.yaml
    volumes:
        - /data:/data
        - /home/saluser/config:/home/saluser/config
    network_mode: "host"
    user: "63001:63001"
