# docker-compose version of this compose file
version: "3.7"

services:
  oods:
    image: lsstts/oods:${OODS_CONTAINER_VERSION}
    build:
      context: ./oods
      args:
        - LSST_STACK_VERSION
        - CTRL_OODS_GIT
        - DM_CSC_BASE_GIT

  test_oods:
    image: lsstts/test_oods
    build:
      context: ./test_oods
      args:
        - LSST_STACK_VERSION
        - DM_CSC_BASE_GIT

  at-oods:
    image: lsstts/oods:${OODS_CONTAINER_VERSION}

  cc-oods:
    image: lsstts/oods:${OODS_CONTAINER_VERSION}

  base:
    image: lsstts/base:${LSSTTS_DEPLOY_ENV_VERSION}
    build:
      context: ./base
      args:
        - TS_SALOBJ_VERSION
        - TS_IDL_VERSION
        - TS_XML_VERSION

  atbase:
    image: lsstts/atbase:${DM_CSC_BASE_VERSION}
    build:
      context: ./atbase
      args:
        - LSSTTS_DEPLOY_ENV_VERSION
        - DM_CONFIG_AT_GIT
        - DM_ATARCHIVER_GIT
        - DM_CSC_BASE_GIT

  atarchiver:
    image: lsstts/atarchiver:${DM_ATARCHIVER_VERSION}
    build:
      context: ./atarchiver
      args:
        - DM_CSC_BASE_VERSION
        - LSSTTS_DEPLOY_ENV_VERSION
    depends_on:
      - atbase

  atcontroller:
    image: lsstts/atcontroller:${DM_ATARCHIVER_VERSION}
    build:
      context: ./atcontroller
      args:
        - DM_CSC_BASE_VERSION
        - LSSTTS_DEPLOY_ENV_VERSION
    depends_on:
      - atbase

  ccbase:
    image: lsstts/ccbase:${DM_CSC_BASE_VERSION}
    build:
      context: ./ccbase
      args:
        - LSSTTS_DEPLOY_ENV_VERSION
        - DM_CONFIG_CC_GIT
        - DM_CCARCHIVER_GIT
        - DM_CSC_BASE_GIT

  ccarchiver:
    image: lsstts/ccarchiver:${DM_CCARCHIVER_VERSION}
    build:
      context: ./ccarchiver
      args:
        - DM_CSC_BASE_VERSION
        - LSSTTS_DEPLOY_ENV_VERSION
    depends_on:
      - ccbase

  cccontroller:
    image: lsstts/cccontroller:${DM_CCARCHIVER_VERSION}
    build:
      context: ./cccontroller
      args:
        - DM_CSC_BASE_VERSION
        - LSSTTS_DEPLOY_ENV_VERSION
    depends_on:
      - ccbase
