# docker-compose version of this compose file
version: "3.7"

services:
  oods:
    image: ts-dockerhub.lsst.org/lsstdm/oods:${OODS_CONTAINER_VERSION}
    build:
      context: ./oods
      args:
        - CYCLE_TAG
        - CTRL_OODS_GIT
        - TS_DDSCONFIG_PACKAGE

  atoods:
    image: ts-dockerhub.lsst.org/lsstdm/atoods:${OODS_CONTAINER_VERSION}
    build:
      context: ./atoods
      args:
        - OODS_CONTAINER_VERSION

  ccoods:
    image: ts-dockerhub.lsst.org/lsstdm/ccoods:${OODS_CONTAINER_VERSION}
    build:
      context: ./ccoods
      args:
        - OODS_CONTAINER_VERSION

  test-oods:
    image: ts-dockerhub.lsst.org/lsstdm/test-oods:${TEST_OODS_CONTAINER_VERSION}
    build:
      context: ./test_oods
      args:
        - TS_DDSCONFIG_PACKAGE
    environment:
        - OODS_CONFIG_FILE=/home/saluser/config/cc_oods.yaml
    volumes:
        - /data:/data
        - /home/saluser/config:/home/saluser/config
    network_mode: "host"
    user: "63001:63001"
