# docker-compose version of this compose file
version: "3.7"

services:
  rabbitmq:
    build:
      context: ./rabbitmq
    container_name: rabbitmq
    hostname: my-rabbit
    ports:
      - "5672:5672"
    networks:
      hostnet: {}

  oods:
    image: lsstts/oods:${OODS_CONTAINER_VERSION}
    build:
      context: ./oods
      args:
        - LSST_STACK_VERSION
        - CTRL_OODS_GIT
        - DM_CSC_BASE_GIT

  test_oods:
    image: lsstts/test_oods
    build:
      context: ./test_oods
      args:
        - LSST_STACK_VERSION
        - DM_CSC_BASE_GIT

  at-oods:
    image: lsstts/oods:${OODS_CONTAINER_VERSION}

  cc-oods:
    image: lsstts/oods:${OODS_CONTAINER_VERSION}

  base:
    image: lsstts/base:${LSSTTS_DEPLOY_ENV_VERSION}
    build:
      context: ./base
      args:
        - TS_SALOBJ_VERSION
        - TS_IDL_VERSION
        - TS_XML_VERSION
        - OPENSPLICE_VERSION

  atbase:
    image: lsstts/atbase:${DM_CSC_BASE_CONTAINER}
    build:
      context: ./atbase
      args:
        - LSSTTS_DEPLOY_ENV_VERSION
        - DM_ATARCHIVER_GIT
        - DM_CSC_BASE_GIT
        - PIKA_VERSION
        - REDIS_VERSION

  atarchiver:
    image: lsstts/atarchiver:${DM_ATARCHIVER_CONTAINER}
    build:
      context: ./atarchiver
      args:
        - DM_CSC_BASE_CONTAINER
        - LSSTTS_DEPLOY_ENV_VERSION
    depends_on:
      - atbase

  atcontroller:
    image: lsstts/atcontroller:${DM_ATARCHIVER_CONTAINER}
    build:
      context: ./atcontroller
      args:
        - DM_CSC_BASE_CONTAINER
        - LSSTTS_DEPLOY_ENV_VERSION
    depends_on:
      - atbase

  ccbase:
    image: lsstts/ccbase:${DM_CSC_BASE_VERSION}_${LSSTTS_DEPLOY_ENV_VERSION}
    build:
      context: ./ccbase
      args:
        - LSSTTS_DEPLOY_ENV_VERSION
        - DM_CCARCHIVER_GIT
        - DM_CSC_BASE_GIT
        - PIKA_VERSION
        - REDIS_VERSION

  ccarchiver:
    image: lsstts/ccarchiver:${DM_CCARCHIVER_CONTAINER}
    build:
      context: ./ccarchiver
      args:
        - DM_CSC_BASE_CONTAINER
        - LSSTTS_DEPLOY_ENV_VERSION
    depends_on:
      - ccbase

  cccontroller:
    image: lsstts/cccontroller:${DM_CCARCHIVER_CONTAINER}
    build:
      context: ./cccontroller
      args:
        - DM_CSC_BASE_CONTAINER
        - LSSTTS_DEPLOY_ENV_VERSION
    depends_on:
      - ccbase

  catchupbase:
    image: lsstts/catchupbase:${DM_CSC_BASE_VERSION}
    build:
      context: ./catchupbase
      args:
        - LSSTTS_DEPLOY_ENV_VERSION
        - DM_CONFIG_CATCHUP_GIT
        - DM_CATCHUPARCHIVER_GIT
        - DM_CSC_BASE_GIT
        - PIKA_VERSION
        - REDIS_VERSION

  catchuparchiver:
    image: lsstts/catchuparchiver:${DM_CATCHUPARCHIVER_VERSION}
    container_name: catchuparchiver
    build:
      context: ./catchuparchiver
      args:
        - DM_CSC_BASE_VERSION
        - LSSTTS_DEPLOY_ENV_VERSION
    environment:
        - IIP_CONFIG_DIR=/home/${USER}/config
        - IIP_CREDENTIAL_DIR=/home/${USER}/.lsst
        - LSST_DDS_DOMAIN
    volumes:
      - /home/${USER}/config:/home/${USER}/config
      - /home/${USER}/.lsst:/home/${USER}/.lsst
      - /var/log/iip:/var/log/iip
      - /data:/data
    networks:
      hostnet: {}
    depends_on:
      - catchupbase

  redis:
    image: redis
    container_name: redis
    hostname: my-redis
    ports:
      - "6379:6379"
    networks:
      hostnet: {}

networks:
  hostnet:
    external: true
    name: host
