# docker-compose version of this compose file
version: "3.7"

# To run:
# export LSST_STACK_VERSION=7-stack-lsst_distrib-w_2019_44
# export OODS_VERSION=1.0.0-rc1

services:
  oods:
    image: oods:${OODS_VERSION}
    build:
      context: ./oods
      args:
        - LSST_STACK_VERSION
        - OODS_VERSION
