# docker-compose version of this compose file
version: "3.7"

services:
  ospl-daemon:
    image: ts-dockerhub.lsst.org/ospl-daemon:${CYCLE_TAG}
    container_name: ospl-daemon
    environment:
      - LSST_DDS_RESPONSIVENESS_TIMEOUT=${LSST_DDS_RESPONSIVENESS_TIMEOUT}
      - LSST_DDS_PARTITION_PREFIX=${SITE_PREFIX}
      - LSST_DDS_INTERFACE=${LSST_DDS_INTERFACE}
      - OSPL_INFOFILE=/tmp/ospl-info-daemon.log
      - OSPL_ERRORFILE=/tmp/ospl-error-daemon.log
      - OSPL_URI=file:///opt/OpenSpliceDDS/V6.10.4/HDE/x86_64.linux/etc/config/ospl.xml
    volumes:
      # NOTE: the docker_tmp directory must exist and be readable and writeable
      # by the UID/GID of the associated container.
      - /tmp/docker_tmp/:/tmp/
      # Necessary if you override parameters in the OSPL config file
      - ./etc/ospl-shmem.xml:/opt/OpenSpliceDDS/V6.10.4/HDE/x86_64.linux/etc/config/ospl.xml
    tty: true
    ipc: host
    pid: host
    # Only necessary if you assign specific IPs to containers.
    #networks:
    #    [network label]:
    #        ipv4_address: "x.x.x.x"
    network_mode: "host"

  oods:
    image: ts-dockerhub.lsst.org/lsstdm/oods:${OODS_CONTAINER_VERSION}
    build:
      context: ./oods
      args:
        - LSST_STACK_VERSION
        - CTRL_OODS_GIT
        - DM_CSC_BASE_GIT

  at-oods:
    image: ts-dockerhub.lsst.org/lsstdm/oods:${OODS_CONTAINER_VERSION}

  cc-oods:
    image: ts-dockerhub.lsst.org/lsstdm/oods:${OODS_CONTAINER_VERSION}

  test_oods:
    image: ts-dockerhub.lsst.org/lsstdm/test_oods
    build:
      context: ./test_oods
      args:
        - LSST_STACK_VERSION
        - DM_CSC_BASE_GIT

  base:
    image: ts-dockerhub.lsst.org/lsstdm/base:${DM_CSC_BASE_VERSION}_${LSSTTS_DEPLOY_ENV_VERSION}
    build:
      context: ./base
      args:
        - CYCLE_TAG
        - PIKA_VERSION
        - REDIS_VERSION
        - TS_DDSCONFIG_PACKAGE
        - DM_CSC_BASE_GIT

  atbase:
    image: ts-dockerhub.lsst.org/lsstdm/atbase:${DM_CSC_BASE_CONTAINER}
    build:
      context: ./atbase
      args:
        - DM_CSC_BASE_CONTAINER
        - DM_ATARCHIVER_GIT
        - DM_CSC_BASE_GIT
        - PIKA_VERSION
        - REDIS_VERSION

  atarchiver:
    image: ts-dockerhub.lsst.org/lsstdm/atarchiver:${DM_ATARCHIVER_CONTAINER}
    build:
      context: ./atarchiver
      args:
        - DM_CSC_BASE_CONTAINER
        - LSSTTS_DEPLOY_ENV_VERSION

  atcontroller:
    image: ts-dockerhub.lsst.org/lsstdm/atcontroller:${DM_ATARCHIVER_CONTAINER}
    build:
      context: ./atcontroller
      args:
        - DM_CSC_BASE_CONTAINER
        - LSSTTS_DEPLOY_ENV_VERSION

  ccbase:
    image: ts-dockerhub.lsst.org/lsstdm/ccbase:${DM_CSC_BASE_CONTAINER}
    build:
      context: ./ccbase
      args:
        - CYCLE_TAG
        - TS_IDL_PACKAGE
        - TS_DDSCONFIG_PACKAGE
        - LSSTTS_DEPLOY_ENV_VERSION
        - DM_CSC_BASE_CONTAINER
        - DM_CCARCHIVER_GIT
        - DM_CSC_BASE_GIT
        - PIKA_VERSION
        - REDIS_VERSION

  ccarchiver:
    image: ts-dockerhub.lsst.org/lsstdm/ccarchiver:${DM_CCARCHIVER_CONTAINER}
    build:
      context: ./ccarchiver
      args:
        - DM_CSC_BASE_CONTAINER
        - LSSTTS_DEPLOY_ENV_VERSION

  cccontroller:
    image: ts-dockerhub.lsst.org/lsstdm/cccontroller:${DM_CCARCHIVER_CONTAINER}
    container_name: cc_controller
    environment:
      - IIP_CONFIG_DIR=/home/saluser/config
      - IIP_CREDENTIAL_DIR=/home/saluser/.lsst
    volumes:
      - /home/saluser/config:/home/saluser/config
      - /home/saluser/.lsst:/home/saluser/.lsst
      - /var/log/iip:/var/log/iip
      - /data:/data
    build:
      context: ./cccontroller
      args:
        - DM_CSC_BASE_CONTAINER
        - LSSTTS_DEPLOY_ENV_VERSION
    network_mode: "host"

  catchupbase:
    image: ts-dockerhub.lsst.org/lsstdm/catchupbase:${DM_CSC_BASE_VERSION}_${LSSTTS_DEPLOY_ENV_VERSION}
    build:
      context: ./catchupbase
      args:
        - LSSTTS_DEPLOY_ENV_VERSION
        - DM_CONFIG_CATCHUP_GIT
        - DM_CATCHUPARCHIVER_GIT
        - DM_CSC_BASE_GIT
        - PIKA_VERSION
        - REDIS_VERSION

  catchuparchiver:
    image: ts-dockerhub.lsst.org/lsstdm/catchuparchiver:${DM_CATCHUPARCHIVER_CONTAINER}
    container_name: catchuparchiver
    build:
      context: ./catchuparchiver
      args:
        - DM_CSC_BASE_CONTAINER
        - LSSTTS_DEPLOY_ENV_VERSION
    environment:
        - IIP_CONFIG_DIR=/home/${USER}/config
        - IIP_CREDENTIAL_DIR=/home/${USER}/.lsst
        - LSST_DDS_PARTITION_PREFIX
    volumes:
      - /home/${USER}/config:/home/${USER}/config
      - /home/${USER}/.lsst:/home/${USER}/.lsst
      - /var/log/iip:/var/log/iip
      - /data:/data
    networks:
      hostnet: {}
    depends_on:
      - catchupbase

  catchupcontroller:
    image: ts-dockerhub.lsst.org/lsstdm/catchupcontroller:${DM_CATCHUPARCHIVER_CONTAINER}
    container_name: catchupcontroller
    build:
      context: ./catchupcontroller
      args:
        - DM_CATCHUPARCHIVER_CONTAINER
    environment:
        - IIP_CONFIG_DIR=/home/${USER}/config
        - IIP_CREDENTIAL_DIR=/home/${USER}/.lsst
    volumes:
      - /home/${USER}/config:/home/${USER}/config
      - /home/${USER}/.lsst:/home/${USER}/.lsst
      - /var/log/iip:/var/log/iip
      - /data:/data
    networks:
      hostnet: {}
      
  redis:
    image: redis
    container_name: redis
    hostname: my-redis
    ports:
      - "6379:6379"
    networks:
      hostnet: {}

  rabbitmq:
    build:
      context: ./rabbitmq
    container_name: rabbitmq
    hostname: my-rabbit
    ports:
      - "5672:5672"
    networks:
      hostnet: {}


networks:
  hostnet:
    external: true
    name: host
